#!/usr/bin/env python3
"""Set up a video work folder: the shared kit, Lucide icons, brand glyphs, and fonts.

Copies kit.css and kit.js from the skill's assets, downloads the icons you
name from jsDelivr, and writes icons.js (window.ICONS for Lucide stroke
icons, window.BRAND for simple-icons filled glyphs). Fonts default to Geist
and Geist Mono (OFL). Stdlib only; needs network access once.

Usage:
  python fetch_assets.py work/ --icons file-text,search,pencil,terminal,git-pull-request --brands github,whatsapp
  python fetch_assets.py work/ --template vertical-chat   # also copy a starter page
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import urllib.request
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
LUCIDE = "https://cdn.jsdelivr.net/npm/lucide-static@1/icons/{}.svg"
SIMPLE = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/{}.svg"
GEIST = "https://cdn.jsdelivr.net/npm/geist@1/dist/fonts/{}"
FONTS = [
    "geist-sans/Geist-Regular.woff2", "geist-sans/Geist-Medium.woff2", "geist-sans/Geist-SemiBold.woff2", "geist-sans/Geist-Bold.woff2",
    "geist-mono/GeistMono-Regular.woff2", "geist-mono/GeistMono-Medium.woff2", "geist-mono/GeistMono-SemiBold.woff2",
]
# The icons the bundled templates use.
DEFAULT_ICONS = [
    "file-text", "search", "pencil", "terminal", "git-pull-request", "git-branch", "shield-check", "check", "check-check",
    "lock", "cpu", "hard-drive", "code", "laptop", "arrow-up", "plus", "camera", "mic", "sticker", "phone", "video",
    "chevron-left", "paperclip", "smile", "folder-git-2", "moon", "send", "key-round", "flask-conical", "message-circle",
    "circle-check", "cloud", "flashlight",
]


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "launch-video-skill"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("work", help="work folder to populate")
    p.add_argument("--icons", default="", help="extra Lucide icon names, comma separated (lucide.dev/icons)")
    p.add_argument("--brands", default="github", help="simple-icons slugs, comma separated (simpleicons.org)")
    p.add_argument("--template", choices=["landscape", "vertical-chat"], action="append", help="copy a starter page")
    p.add_argument("--no-fonts", action="store_true")
    args = p.parse_args()

    work = Path(args.work)
    work.mkdir(parents=True, exist_ok=True)
    for name in ("kit.css", "kit.js"):
        shutil.copy(SKILL / "assets/kit" / name, work / name)
    for t in args.template or []:
        dest = work / f"{t}.html"
        if dest.exists():
            print(f"kept existing {dest}")
        else:
            shutil.copy(SKILL / "assets/templates" / f"{t}.html", dest)

    icons, brands = {}, {}
    names = DEFAULT_ICONS + [n.strip() for n in args.icons.split(",") if n.strip()]
    for name in dict.fromkeys(names):
        try:
            svg = get(LUCIDE.format(name)).decode()
        except OSError as e:
            print(f"icon {name}: {e}", file=sys.stderr)
            continue
        inner = re.search(r"<svg[^>]*>(.*)</svg>", re.sub(r"<!--.*?-->", "", svg, flags=re.S), re.S).group(1)
        icons[name] = re.sub(r"\s+", " ", inner).strip()
    for slug in [b.strip() for b in args.brands.split(",") if b.strip()]:
        try:
            svg = get(SIMPLE.format(slug)).decode()
            brands[slug] = re.search(r'<path d="([^"]+)"', svg).group(1)
        except (OSError, AttributeError) as e:
            print(f"brand {slug}: {e}", file=sys.stderr)
    (work / "icons.js").write_text(
        "// generated by fetch_assets.py: Lucide (ISC) and simple-icons (CC0)\n"
        f"window.ICONS = {json.dumps(icons)};\nwindow.BRAND = {json.dumps(brands)};\n"
    )
    if not args.no_fonts:
        for f in FONTS:
            dest = work / Path(f).name
            if not dest.exists():
                dest.write_bytes(get(GEIST.format(f)))
    print(f"{work}: kit, {len(icons)} icons, {len(brands)} brand glyphs{'' if args.no_fonts else ', Geist fonts'}")


if __name__ == "__main__":
    main()
